@startuml
'https://plantuml.com/class-diagram
'https://plantuml.com/guide

rectangle Chess-layer {

    together {
        rectangle {
            class ChessException {
                + ChessException(String : msg) : void
            }

            enum Color {
                - BLACK : int
                - WHITE : int
            }

            class ChessPosition {
                - colum : char
                - row : int
                # toPosition() : Position
                # fromPosition(position : Position) : ChessPosition
            }

            Color -[hidden]> ChessPosition
        }
    }

    ChessException -[hidden]--> ChessMatch
    ChessMatch -[hidden]> ChessPiece

    together {
        class ChessMatch {
            - turn : int
            - currentPlayer : Color
            - check : boolean
            - checkMate : boolean
            - enPassantVulnerable : ChessPiece
            - promoted : chessPiece
            + getPieces() : ChessPiece[][]
            + possibleMoves(sourcePosition : ChessPosition) : boolean[][]
            + performChessMove(sourcePosition : ChessPosition, targetPosition : ChessPosition) : ChessPosition
            + replacePromotedPiece(type : String) :ChessPiece
        }

        ChessMatch -[hidden]-> ChessPiece

        class ChessPiece {
            - color : Color
            - moveCount : int
            + getChessPosition() : ChessPosition
            # isThereOpponentPiece(position : Position) : boolean
            # increaseMoveCount() : void
            # decreaseMoveCount() : void
        }

        class King extends ChessPiece
        class Bishop extends ChessPiece
        class Knight extends ChessPiece
        class Pawn extends ChessPiece
        class Queen extends ChessPiece
        class Rook extends ChessPiece
        King --> ChessMatch : 1 chessMatch
        Pawn --> ChessMatch : 1 chessMatch
    }
}
@enduml